### ISSUE TITLE
Wrong name is displayed

### ISSUE THREAD

**Issue by ItsMacs** [ImOnlyFire/YukiGram#1]
**Bug Description**
In the app splash, the name "YukiGram" is displayed instead of "LoliGram"

**To Reproduce**
Download the app and open it

**Application Crash**
Unfortunately not

**Comment by ImOnlyFire** [comment]
Next update I swear

**Comment by ItsMacs** [comment]
Thanks fam I appreciate
Hey when are you buying Twitter Blue bro i love it

**Comment by Repressoh** [comment]
@ImOnlyFire 🔥

**Comment by LK024** [comment]
@ItsMacs Commento di prova ora che ho collegato l'account
